version: "3"

services:
    mongodb:
        container_name: mongodb
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - /home/mtx22/mongodb/database:/data/db
        environment:
            - MONGO_INITDB_DATABASE=local
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=secr3t
    backend:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ../../backend
        ports:
            - "5000:5000"
        depends_on:
            - "mongodb"
        environment:
            - MONGO_HOST=mongodb
            - MONGO_PORT=27017
            - MONGO_DATABASE=local
            - MONGO_USERNAME=user
            - MONGO_PASSWORD=secr3t
        volumes:
            - ../../backend:/app
    backend_containers:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ../../backend_containers
        ports:
            - "5001:5001"
        depends_on:
            - "javascript"
            - "python"
            - "bash"
            - "java"
            - "cpp"
            - "c"
            - "r"
        volumes:
            - ../../backend_containers:/app
    javascript:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ../../containers/javascript
        ports:
            - "6000:5000"
    python:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ../../containers/python
        ports:
            - "6001:5000"
    bash:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ../../containers/bash
        ports:
            - "6002:5000"
    java:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ../../containers/java
        ports:
            - "6003:5000"
    cpp:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ../../containers/cpp
        ports:
            - "6004:5000"
    c:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ../../containers/c
        ports:
            - "6005:5000"
    r:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ../../containers/r
        ports:
            - "6006:5000"
    frontend:
        build:
            dockerfile: Dockerfile.dev
            context: ../../frontend
        depends_on:
            - "backend"
            - "backend_containers"
        ports:
            - "3000:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ../../frontend/node_modules:/app/node_modules
            - ../../frontend:/app
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ../../nginx
        ports:
            - "9090:80"

    auth0:
        restart: always
        image: yannj/auth0-docker:latest
        environment:
            - AUTH0_CLIENT_ID=S78rEYoT9kikIwcv3l0AI1Lg49AxSmMb
            - AUTH0_DOMAIN=dev-v6t-co5x.us.auth0.com
            - AUTH0_CLIENT_SECRET=c-aZ9-dAmNzjT7c0D7yfxwZ4vo8n2e2te9_qEF5yX-XoSHjRcY64DgWLbPF8dkq3
