version: '3'

services:
  mongodb:
    restart: always
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - /home/${USER}/mongodb/database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=secr3t
    networks:
      - no-internet
  backend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ../../backend
    depends_on:
      - 'mongodb'
    environment:
      - PORT=5000
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=secr3t
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=secr3t
      - APP_DOMAIN=dev-v6t-co5x.us.auth0.com
      - APP_CONTAINERS_ADDRESS=http://backend_containers:5001
      - APP_AUDIENCE=http://localhost:5000
      - WEBSOCKET_PORT=5002
      - APP_CONTAINERS_CLIENT_ID=dzGcSwBjm0Roj6eZhnc1tjC284q242fW
      - APP_CONTAINERS_CLIENT_SECRET=1ZgtLjP2kkJpJGK8xQ2uqCoJuKcZxCgiJVuBUFbY83MLHXlgEYGoro2y8zdsOLLz
    volumes:
      - ../../backend:/opt/app
    ports:
      - '5000:5000'
      - '5002:5002'
    networks:
      - no-internet
      - internet
  backend_containers:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ../../backend_containers
    depends_on:
      - 'javascript'
      - 'python'
      - 'bash'
      - 'java'
      - 'cpp'
      - 'c'
      - 'r'
    volumes:
      - ../../backend_containers:/opt/app
    ports:
      - '5001:5001'
    environment:
      - APP_AUDIENCE=http://localhost:5000
      - APP_DOMAIN=dev-v6t-co5x.us.auth0.com
    networks:
      - no-internet
      - internet
  javascript:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../../containers/javascript
    environment:
      - PORT=6000
      - TIMEOUT=30000
    ports:
      - '6000:6000'
    networks:
      - no-internet
  python:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../../containers/python
    environment:
      - PORT=6001
      - TIMEOUT=30000
    ports:
      - '6001:6001'
    networks:
      - no-internet
  bash:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../../containers/bash
    environment:
      - PORT=6002
      - TIMEOUT=30000
    ports:
      - '6002:6002'
    networks:
      - no-internet
  r:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../../containers/r
    environment:
      - PORT=6003
      - TIMEOUT=30000
    ports:
      - '6003:6003'
    networks:
      - no-internet
  java:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../../containers/java
    environment:
      - PORT=6004
      - TIMEOUT=30000
    ports:
      - '6004:6004'
    networks:
      - no-internet
  cpp:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../../containers/cpp
    environment:
      - PORT=6005
      - TIMEOUT=30000
    ports:
      - '6005:6005'
    networks:
      - no-internet
  c:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../../containers/c
    environment:
      - PORT=6006
      - TIMEOUT=30000
    ports:
      - '6006:6006'
    networks:
      - no-internet
  frontend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ../../frontend
    depends_on:
      - 'backend'
      - 'backend_containers'
    ports:
      - '3000:3000'
    volumes:
      - ../../frontend/node_modules:/opt/app/node_modules
      - ../../frontend:/opt/app
    environment:
      - REACT_APP_BACKEND_CLIENT_ID=dzGcSwBjm0Roj6eZhnc1tjC284q242fW
      - REACT_APP_BACKEND_CLIENT_SECRET=1ZgtLjP2kkJpJGK8xQ2uqCoJuKcZxCgiJVuBUFbY83MLHXlgEYGoro2y8zdsOLLz
      - REACT_APP_DOMAIN=dev-v6t-co5x.us.auth0.com
      - REACT_APP_CLIENT_ID=S78rEYoT9kikIwcv3l0AI1Lg49AxSmMb
      - REACT_APP_CONTAINERS_ADDRESS=http://localhost:5001
      - REACT_APP_BACKEND=http://localhost:5000
      - REACT_APP_REDIRECT_URI=http://localhost:3000
      - REACT_APP_WEBSOCKET_ADDRESS=http://localhost:5002/
      - REACT_APP_LOGOUT_URL=http://localhost:3000
    networks:
      - no-internet
      - internet
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --requirepass secr3t
    networks:
      - no-internet
networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
