const REDIRECT_AFTER_ADD_EX_START = 'REDIRECT_AFTER_ADD_EX_START';
const REDIRECT_AFTER_ADD_EX_FINISHED = 'REDIRECT_AFTER_ADD_EX_FINISHED';

export const types = {
  REDIRECT_AFTER_ADD_EX_START,
  REDIRECT_AFTER_ADD_EX_FINISHED,
};
