# FROM node:16.13.0-alpine as builder
# WORKDIR /opt/app
# COPY ./package.json ./
# RUN yarn install
# COPY . .

# FROM node:16.13.0-alpine
# WORKDIR /opt/app
# COPY --from=builder /opt/app  .
# CMD ["yarn","dev"]

FROM node:alpine as build-stage
WORKDIR /opt/app
COPY ./package.json ./
RUN yarn install
COPY ./ ./
ENV REACT_APP_CONTAINERS_ADDRESS "\\\${REACT_APP_CONTAINERS_ADDRESS}"
ENV REACT_APP_BACKEND "\\\${REACT_APP_BACKEND}"
ENV REACT_APP_REDIRECT_URI "\\\${REACT_APP_REDIRECT_URI}"
ENV REACT_APP_DOMAIN "\\\${REACT_APP_DOMAIN}"
ENV REACT_APP_CLIENT_ID "\\\${REACT_APP_CLIENT_ID}"
ENV REACT_APP_CONTAINERS_CLIENT_ID "\\\${REACT_APP_CONTAINERS_CLIENT_ID}"
ENV REACT_APP_CONTAINERS_CLIENT_SECRET "\\\${REACT_APP_CONTAINERS_CLIENT_SECRET}"
RUN rm -f .env* ; \
    printenv > .env && \
    yarn build

FROM nginx:alpine as nginx
COPY --from=build-stage /opt/app/build /usr/share/nginx/html
COPY --from=build-stage /opt/app/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /opt/app/.cert/key.pem /usr/share/nginx/certs/key.pem
COPY --from=build-stage /opt/app/.cert/cert.crt /usr/share/nginx/certs/cert.crt
RUN echo "\
export ENV_LIST=\"\$(printenv | awk -F= '{print $1}' | sed 's/^/\$/g' | paste -sd,)\"; \
find /usr/share/nginx/html/static/ -type f -name \"*.js\"| \
xargs -I % sh -c 'envsubst \"\${ENV_LIST}\" < \"%\" > \"%.tmp\" && mv \"%.tmp\" \"%\"'" \
> /docker-entrypoint.d/40-envsubst-react-environment.sh && chmod +x /docker-entrypoint.d/40-envsubst-react-environment.sh