const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE';

const POST_NOTIFICATION_REQUEST = 'POST_NOTIFICATION_REQUEST';
const POST_NOTIFICATION_SUCCESS = 'POST_NOTIFICATION_SUCCESS';
const POST_NOTIFICATION_FAILURE = 'POST_NOTIFICATION_FAILURE';

const READ_NOTIFICATION_REQUEST = 'READ_NOTIFICATION_REQUEST';
const READ_NOTIFICATION_SUCCESS = 'READ_NOTIFICATION_SUCCESS';
const READ_NOTIFICATION_FAILURE = 'READ_NOTIFICATION_FAILURE';

export const types = {
  GET_NOTIFICATIONS_REQUEST,
  GET_NOTIFICATIONS_SUCCESS,
  GET_NOTIFICATIONS_FAILURE,
  POST_NOTIFICATION_REQUEST,
  POST_NOTIFICATION_SUCCESS,
  POST_NOTIFICATION_FAILURE,
  READ_NOTIFICATION_REQUEST,
  READ_NOTIFICATION_SUCCESS,
  READ_NOTIFICATION_FAILURE,
};
