apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth0-deployment
    namespace: production
    labels:
        app: codely
        type: auth0
spec:
    selector:
        matchLabels:
            app: codely
            type: auth0
    replicas: 2
    template:
        metadata:
            name: auth0-pod
            labels:
                app: codely
                type: auth0
        spec:
            containers:
                - name: auth0-container
                  image: yannj/auth0-docker:latest
                  env:
                      - name: AUTH0_CLIENT_ID
                        valueFrom:
                            secretKeyRef:
                                name: auth0-secret
                                key: AUTH0_CLIENT_ID
                      - name: AUTH0_DOMAIN
                        valueFrom:
                            secretKeyRef:
                                name: auth0-secret
                                key: AUTH0_DOMAIN
                      - name: AUTH0_CLIENT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: auth0-secret
                                key: AUTH0_CLIENT_SECRET
