apiVersion: apps/v1
kind: Deployment
metadata:
  name: bash-container-deployment
  namespace: production
  labels:
    app: codely
    type: bash-container
spec:
  selector:
    matchLabels:
      app: codely
      type: bash-container
  replicas: 2
  template:
    metadata:
      name: bash-container-pod
      labels:
        app: codely
        type: bash-container
    spec:
      containers:
        - name: bash-container
          image: mtx22/codely-bash
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: BASH_PORT
                  name: containers-configmap
