apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-container-deployment
  namespace: production
  labels:
    app: codely
    type: cpp-container
spec:
  selector:
    matchLabels:
      app: codely
      type: cpp-container
  replicas: 1
  template:
    metadata:
      name: cpp-container-pod
      labels:
        app: codely
        type: cpp-container
    spec:
      containers:
        - name: cpp-container
          image: mtx22/codely-cpp
          resources:
            requests:
              memory: '50Mi'
              cpu: '100m'
            limits:
              memory: '100Mi'
              cpu: '1000m'
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: CPP_PORT
                  name: containers-configmap
            - name: TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: TIMEOUT
                  name: containers-configmap
