apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
    namespace: production
    labels:
        app: codely
        type: frontend
spec:
    selector:
        matchLabels:
            app: codely
            type: frontend
    replicas: 2
    template:
        metadata:
            name: frontend-pod
            labels:
                app: codely
                type: frontend
        spec:
            containers:
                - name: frontend-container
                  # TODO Add image name
                  image: image_name
                  ports:
                      - containerPort: 80
                  env:
                      - name: REACT_APP_CONTAINERS_ADDRESS
                        valueFrom:
                            configMapKeyRef:
                                key: REACT_APP_CONTAINERS_ADDRESS
                                name: frontend-configmap
                      - name: REACT_APP_BACKEND
                        valueFrom:
                            configMapKeyRef:
                                key: REACT_APP_BACKEND
                                name: frontend-configmap
                      - name: REACT_APP_ADDRESS
                        valueFrom:
                            configMapKeyRef:
                                key: REACT_APP_ADDRESS
                                name: frontend-configmap
                      - name: REACT_APP_DOMAIN
                        valueFrom:
                            secretKeyRef:
                                name: frontend-secret
                                key: REACT_APP_DOMAIN
                      - name: REACT_APP_CLIENT_ID
                        valueFrom:
                            secretKeyRef:
                                name: frontend-secret
                                key: REACT_APP_CLIENT_ID
                      - name: REACT_APP_CONTAINERS_CLIENT_ID
                        valueFrom:
                            secretKeyRef:
                                name: frontend-secret
                                key: REACT_APP_CONTAINERS_CLIENT_ID
                      - name: REACT_APP_CONTAINERS_CLIENT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: frontend-secret
                                key: REACT_APP_CONTAINERS_CLIENT_SECRET
