apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
    namespace: production
    labels:
        app: codely
        type: frontend
spec:
    selector:
        matchLabels:
            app: codely
            type: frontend
    replicas: 2
    template:
        metadata:
            name: frontend-pod
            labels:
                app: codely
                type: frontend
        spec:
            containers:
                - name: frontend-container
                  # TODO Add image name
                  image: image_name
                  ports:
                      - containerPort: 80
