apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongodb-deployment
  namespace: production
  labels:
    run: mongodb-deployment

spec:
  template:
    metadata:
      name: mongodb-deployment
      labels:
        run: mongodb-deployment
    spec:
      containers:
        - name: mongodb-deployment
          image: mongo
          args: ['--dbpath', '/data/db']
          volumeMounts:
            - name: mongodbvolume
              mountPath: /data/db
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: mongodb-configmap
            - secretRef:
                name: mongodb-secret
      volumes:
        - name: mongodbvolume
          persistentVolumeClaim:
            claimName: mongodb-pvc
  replicas: 1
  selector:
    matchLabels:
      run: mongodb-deployment
