apiVersion: apps/v1
kind: Deployment

metadata:
    name: mongodb-deployment
    namespace: production
    labels:
        run: mongodb-deployment

spec:
    template:
        metadata:
            name: mongodb-deployment
            labels:
                run: mongodb-deployment
        spec:
            containers:
                - name: mongodb-deployment
                  image: mongo
                  args: ['--dbpath', '/data/db']
                  volumeMounts:
                      - name: mongodbvolume
                        mountPath: /data/db
                  ports:
                      - containerPort: 27017
                  env:
                      - name: MONGO_INITDB_DATABASE
                        valueFrom:
                            configMapKeyRef:
                                key: MONGO_INITDB_DATABASE
                                name: mongodb-configmap
                      - name: MONGO_INITDB_ROOT_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-secret
                                key: MONGO_INITDB_ROOT_USERNAME
                      - name: MONGO_INITDB_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-secret
                                key: MONGO_INITDB_ROOT_PASSWORD
            volumes:
                - name: mongodbvolume
                  persistentVolumeClaim:
                      claimName: mongodb-pvc
    replicas: 1
    selector:
        matchLabels:
            run: mongodb-deployment
