apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongodb-deployment
  namespace: production
  labels:
    run: mongodb-deployment

spec:
  template:
    metadata:
      name: mongodb-deployment
      labels:
        run: mongodb-deployment
    spec:
      containers:
        - name: mongodb-deployment
          image: mongo:latest
          resources:
            requests:
              memory: '200Mi'
              cpu: '50m'
            limits:
              memory: '800Mi'
              cpu: '200m'
          args: ['--dbpath', '/data/db']
          volumeMounts:
            - name: mongodbvolume
              mountPath: /data/db
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongodb-secret
      volumes:
        - name: mongodbvolume
          persistentVolumeClaim:
            claimName: mongodb-pvc
  replicas: 1
  selector:
    matchLabels:
      run: mongodb-deployment
