apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-container-deployment
  namespace: production
  labels:
    app: codely
    type: python-container
spec:
  selector:
    matchLabels:
      app: codely
      type: python-container
  replicas: 2
  template:
    metadata:
      name: python-container-pod
      labels:
        app: codely
        type: python-container
    spec:
      containers:
        - name: python-container
          image: mtx22/codely-python
          resources:
            requests:
              memory: '50Mi'
              cpu: '10m'
            limits:
              memory: '200Mi'
              cpu: '70m'
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PYTHON_PORT
                  name: containers-configmap
            - name: TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: TIMEOUT
                  name: containers-configmap
