apiVersion: apps/v1
kind: Deployment
metadata:
    name: r-container-deployment
    namespace: production
    labels:
        app: codely
        type: r-container
spec:
    selector:
        matchLabels:
            app: codely
            type: r-container
    replicas: 2
    template:
        metadata:
            name: r-container-pod
            labels:
                app: codely
                type: r-container
        spec:
            containers:
                - name: r-container
                  image: mtx22/codely-r
                  env:
                      - name: PORT
                        valueFrom:
                            configMapKeyRef:
                                key: R_PORT
                                name: containers-configmap
