apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: production
  labels:
    run: redis-deployment
spec:
  template:
    metadata:
      name: redis-deployment
      labels:
        run: redis-deployment
    spec:
      containers:
        - name: redis-deployment
          image: redis:latest
          ports:
            - containerPort: 6379
          envFrom:
            - secretRef:
                name: redis-secret
          args: ['--requirepass', '$(REDIS_PASSWORD)']
  replicas: 1
  selector:
    matchLabels:
      run: redis-deployment
