const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
const GET_TOKEN_REQUEST = 'GET_TOKEN_REQUEST';
const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE';

export const types = {
  GET_TOKEN_REQUEST,
  GET_TOKEN_SUCCESS,
  GET_TOKEN_FAILURE,
};
