apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-pv-prod
    namespace: production
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 50Mi
    accessModes:
        - ReadWriteOnce
    hostPath:
        #    Path dla linux - nie działa
        path: '/mnt/data/production/mongodb'
        #    Path dla Windows - działa
        #    path: '/run/desktop/mnt/host/mongodb'
    claimRef:
        name: mongodb-pvc
        namespace: production
