kind: Service
apiVersion: v1
metadata:
    name: auth0
    namespace: production
spec:
    type: ClusterIP
    ports:
        - port: 3000
          targetPort: 3000
          protocol: TCP
    selector:
        app: codely
        type: auth0
