kind: Service
apiVersion: v1
metadata:
    name: backend
    namespace: production
spec:
    type: ClusterIP
    ports:
        - port: 5000
          targetPort: 5000
          protocol: TCP
    selector:
        app: codely
        type: backend
