kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: production
spec:
  type: ClusterIP
  ports:
    - name: backend
      port: 5000
      targetPort: 5000
      protocol: TCP
    - name: websocket
      port: 5002
      targetPort: 5002
      protocol: TCP
  selector:
    app: codely
    type: backend
