kind: Service
apiVersion: v1
metadata:
    name: bash-container-service
    namespace: production
spec:
    type: ClusterIP
    ports:
        - port: 6002
          targetPort: 6002
          protocol: TCP
    selector:
        app: codely
        type: bash-container
