kind: Service
apiVersion: v1
metadata:
    name: cpp-container-service
    namespace: production
spec:
    type: ClusterIP
    ports:
        - port: 6005
          targetPort: 6005
          protocol: TCP
    selector:
        app: codely
        type: cpp-container
