kind: Service
apiVersion: v1
metadata:
    name: frontend-service
    namespace: production
spec:
    type: ClusterIP
    ports:
        - port: 80
          targetPort: 80
          protocol: TCP
    selector:
        app: codely
        type: frontend
