kind: Service
apiVersion: v1
metadata:
  name: java
  namespace: production
spec:
  type: ClusterIP
  ports:
    - port: 6004
      targetPort: 6004
      protocol: TCP
  selector:
    app: codely
    type: java-container
