kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: production
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    run: mongodb-deployment
