kind: Service
apiVersion: v1
metadata:
    name: python-container-service
    namespace: production
spec:
    type: ClusterIP
    ports:
        - port: 6001
          targetPort: 6001
          protocol: TCP
    selector:
        app: codely
        type: python-container
