kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: production
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    run: redis-deployment
