apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress
    namespace: production
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
    rules:
        - host: codely.io
          http:
              paths:
                  - path: /(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: frontend
                            port:
                                number: 80
                  - path: /user?(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: frontend
                            port:
                                number: 80
    tls:
        - hosts:
              - codely.io
