apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress
    namespace: production
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        # nginx.ingress.kubernetes.io/auth-url: 'https://codely.prod/oauth2/auth'
        # nginx.ingress.kubernetes.io/auth-signin: 'https://codely.prod/oauth2/start?rd=$escaped_request_uri'
spec:
    rules:
        - host: codely.io
          http:
              paths:
                  - path: /(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: frontend
                            port:
                                number: 80
