apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    nginx.ingress.kubernetes.io/websocket-services: 'backend'
    nginx.org/websocket-services: 'backend'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /user?(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000
          - path: /websocket/(.*)
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5002
          - path: /socket.io/(.*)
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5002
          - path: /containers/(.*)
            pathType: Prefix
            backend:
              service:
                name: backend-containers
                port:
                  number: 5001
