apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress
    namespace: production
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
    rules:
        - host: codely.prod
          http:
              paths:
                  - path: /(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: frontend
                            port:
                                number: 80
                  #   - path: /(.*)
                  #     pathType: Prefix
                  #     backend:
                  #         service:
                  #             name: backend-service
                  #             port:
                  #                 number: 5000
                  #   - path: /(.*)
                  #     pathType: Prefix
                  #     backend:
                  #         service:
                  #             name: backend-containers-service
                  #             port:
                  #                 number: 5001
                  #   - path: /(.*)
                  #     pathType: Prefix
                  #     backend:
                  #         service:
                  #             name: auth0-service
                  #             port:
                  #                 number: 3000
