apiVersion: v1
kind: ConfigMap

metadata:
    name: backend-configmap
    namespace: production
data:
    MONGO_HOST: mongodb
    MONGO_PORT: '27017'
    MONGO_DATABASE: local
    PORT: '5000'
    APP_BACKEND_CONTAINERS: http://backend-containers:5001
    APP_AUDIENCE: http://localhost:5000
