apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-configmap
  namespace: production
data:
  PORT: '5000'
  MONGO_HOST: mongodb
  MONGO_PORT: '27017'
  REDIS_PORT: '6379'
  REDIS_HOST: redis
  APP_CONTAINERS_ADDRESS: http://backend-containers:5001
  WEBSOCKET_PORT: '5002'
