apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-configmap
  namespace: production
data:
  MONGO_HOST: mongodb
  MONGO_PORT: '27017'
  MONGO_DATABASE: local
  PORT: '5000'
  APP_BACKEND_CONTAINERS: https://backend-containers:5001
  APP_AUDIENCE: https://backend:5000
  APP_CONTAINERS_ADDRESS: https://backend-containers:5001
