apiVersion: v1
kind: ConfigMap

metadata:
    name: frontend-configmap
    namespace: production
data:
    REACT_APP_CONTAINERS_ADDRESS: http://backend-containers:5001
    REACT_APP_BACKEND: http://localhost:5000/api
    REACT_APP_REDIRECT_URI: https://codely.io
