apiVersion: v1
kind: ConfigMap

metadata:
  name: frontend-configmap
  namespace: production
data:
  REACT_APP_CONTAINERS_ADDRESS: https://backend-containers:5001
  REACT_APP_BACKEND: https://backend:5000
  REACT_APP_REDIRECT_URI: https://codely.io
