apiVersion: v1
kind: ConfigMap

metadata:
    name: frontend-configmap
    namespace: production
data:
    REACT_APP_CONTAINERS_ADDRESS: http://localhost:5001
    REACT_APP_BACKEND: http://localhost:5000
    REACT_APP_ADDRESS: http://localhost:3000
