const GET_EXERCISES_SUCCESS = 'GET_EXERCISES_SUCCESS';
const GET_EXERCISES_REQUEST = 'GET_EXERCISES_REQUEST';
const GET_EXERCISES_FAILURE = 'GET_EXERCISES_FAILURE';

const POST_EXERCISE_SUCCESS = 'POST_EXERCISE_SUCCESS';
const POST_EXERCISE_REQUEST = 'POST_EXERCISE_REQUEST';
const POST_EXERCISE_FAILURE = 'POST_EXERCISE_FAILURE';

const DELETE_EXERCISE_REQUEST = 'DELETE_EXERCISE_REQUEST';
const DELETE_EXERCISE_SUCCESS = 'DELETE_EXERCISE_SUCCESS';
const DELETE_EXERCISE_FAILURE = 'DELETE_EXERCISE_FAILURE';

export const types = {
  GET_EXERCISES_REQUEST,
  GET_EXERCISES_SUCCESS,
  GET_EXERCISES_FAILURE,
  POST_EXERCISE_REQUEST,
  POST_EXERCISE_SUCCESS,
  POST_EXERCISE_FAILURE,
  DELETE_EXERCISE_REQUEST,
  DELETE_EXERCISE_SUCCESS,
  DELETE_EXERCISE_FAILURE,
};
