const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST';
const GET_REVIEWS_FAILURE = 'GET_REVIEWS_FAILURE';

const POST_REVIEWS_SUCCESS = 'POST_REVIEWS_SUCCESS';
const POST_REVIEWS_REQUEST = 'POST_REVIEWS_REQUEST';
const POST_REVIEWS_FAILURE = 'POST_REVIEWS_FAILURE';

const EDIT_REVIEW_SUCCESS = 'EDIT_REVIEW_SUCCESS';
const EDIT_REVIEW_REQUEST = 'EDIT_REVIEW_REQUEST';
const EDIT_REVIEW_FAILURE = 'EDIT_REVIEW_FAILURE';

const UPVOTE_REVIEW_SUCCESS = 'UPVOTE_REVIEW_SUCCESS';
const UPVOTE_REVIEW_REQUEST = 'UPVOTE_REVIEW_REQUEST';
const UPVOTE_REVIEW_FAILURE = 'UPVOTE_REVIEW_FAILURE';

const DOWNVOTE_REVIEW_SUCCESS = 'DOWNVOTE_REVIEW_SUCCESS';
const DOWNVOTE_REVIEW_REQUEST = 'DOWNVOTE_REVIEW_REQUEST';
const DOWNVOTE_REVIEW_FAILURE = 'DOWNVOTE_REVIEW_FAILURE';


export const types = {
  GET_REVIEWS_REQUEST,
  GET_REVIEWS_SUCCESS,
  GET_REVIEWS_FAILURE,
  POST_REVIEWS_REQUEST,
  POST_REVIEWS_SUCCESS,
  POST_REVIEWS_FAILURE,
  EDIT_REVIEWS_FAILURE,
  EDIT_REVIEWS_REQUEST,
  EDIT_REVIEWS_SUCCESS,
  UPVOTE_REVIEW_FAILURE,
  UPVOTE_REVIEW_REQUEST,
  UPVOTE_REVIEW_SUCCESS,
  DOWNVOTE_REVIEW_FAILURE,
  DOWNVOTE_REVIEW_REQUEST,
  DOWNVOTE_REVIEW_SUCCESS,
};
