const ADD_EXERCISE = 'ADD_EXERCISE';
const DELETE_EXERCISE = 'DELETE_EXERCISE';
const UPDATE_EXERCISE = 'UPDATE_EXERCISE';

export const types = {
  ADD_EXERCISE,
  DELETE_EXERCISE,
  UPDATE_EXERCISE,
};
