const ADD_EXERCISE = 'ADD_EXERCISE';
const DELETE_EXERCISE = 'DELETE_EXERCISE';
const UPDATE_EXERCISE = 'UPDATE_EXERCISE';

const ADD_EXERCISE_CLOSE = 'ADD_EXERCISE_CLOSE';
const DELETE_EXERCISE_CLOSE = 'DELETE_EXERCISE_CLOSE';
const UPDATE_EXERCISE_CLOSE = 'UPDATE_EXERCISE_CLOSE';

export const types = {
  ADD_EXERCISE,
  DELETE_EXERCISE,
  UPDATE_EXERCISE,
  ADD_EXERCISE_CLOSE,
  DELETE_EXERCISE_CLOSE,
  UPDATE_EXERCISE_CLOSE,
};
