name: Prettier
on: [push]

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Prettify code
              uses: creyD/prettier_action@v4.2
              with:
                  prettier_options: --single-quote --write **/*.{html,css,scss,yaml,json,jsx,js,md}
                  only_changed: True
                  same_commit: True
