const GET_USERS_REQUEST = 'GET_USER_REQUEST';
const GET_USERS_SUCCESS = 'GET_USER_SUCCESS';
const GET_USERS_FAILURE = 'GET_USER_FAILURE';

const POST_USER_REQUEST = 'POST_USER_REQUEST';
const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
const POST_USER_FAILURE = 'POST_USER_FAILURE';

export const types = {
  GET_USERS_REQUEST,
  GET_USERS_SUCCESS,
  GET_USERS_FAILURE,
  POST_USER_REQUEST,
  POST_USER_SUCCESS,
  POST_USER_FAILURE,
};
